# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monstarillo < Formula
  desc "A code generator"
  homepage "https://github.com/monstarillo/monstarillo"
  version "0.0.302"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.302/monstarillo_0.0.302_darwin_amd64.tar.gz"
      sha256 "a1cb8b63f4ebf1091a2df3f87572a333b16b99aa218389c93b4bca8c787c80a3"

      def install
        bin.install "monstarillo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.302/monstarillo_0.0.302_darwin_arm64.tar.gz"
      sha256 "db00639b8993b0ce752758913bec6f95a579d40f62cd4b975ab046fcc9780607"

      def install
        bin.install "monstarillo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.302/monstarillo_0.0.302_linux_amd64.tar.gz"
        sha256 "f5cd3b14a7056ec2b1053087ed014d512be8731059e08b3684a5b9efaf4b9442"

        def install
          bin.install "monstarillo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.302/monstarillo_0.0.302_linux_arm64.tar.gz"
        sha256 "ed89e375358f16d4c5e25386db232769d22836986792bf6a4151351dd2c55e0f"

        def install
          bin.install "monstarillo"
        end
      end
    end
  end

  test do
    system "#{bin}monstarillo mysql --help"
  end
end
