# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monstarillo < Formula
  desc "A code generator"
  homepage "https://github.com/monstarillo/monstarillo"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.9/monstarillo_0.0.9_Darwin_x86_64.tar.gz"
      sha256 "eb00d06f177dfe78e4c6ee4f94f9cac8e1ce9a1555f8d7e614399cf675d001cc"

      def install
        bin.install "monstarillo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.9/monstarillo_0.0.9_Darwin_arm64.tar.gz"
      sha256 "12864158e21f199f7ae2e807920e070b0e2a274fd8c7e5f867f3dec287dbbc56"

      def install
        bin.install "monstarillo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.9/monstarillo_0.0.9_Linux_arm64.tar.gz"
      sha256 "2cca92184f16f8c14890ca4234138123bbfadfac6d13b3f87e93574ef9a3fe0d"

      def install
        bin.install "monstarillo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.9/monstarillo_0.0.9_Linux_x86_64.tar.gz"
      sha256 "a8ab16d86e84ae8b484fed05675c28459a959b061440caaeeddd0a4a45e60a79"

      def install
        bin.install "monstarillo"
      end
    end
  end

  test do
    system "#{bin}monstarillo mysql --help"
  end
end
