# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monstarillo < Formula
  desc "A code generator"
  homepage "https://github.com/monstarillo/monstarillo"
  version "0.0.301"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.301/monstarillo_0.0.301_darwin_amd64.tar.gz"
      sha256 "07cb98f8ba968532003deccf1d16ddf83ce55f4560a95f820a0097b1dd02713b"

      def install
        bin.install "monstarillo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.301/monstarillo_0.0.301_darwin_arm64.tar.gz"
      sha256 "e2abc62a039665afbbbcfa292cc202416f26eebcb0341c7edfeeeb6e035710bc"

      def install
        bin.install "monstarillo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.301/monstarillo_0.0.301_linux_amd64.tar.gz"
        sha256 "1019abc4ab02c08f81da2b4849a2717ed580b7e3a8538a2b1f57d9d23ed51729"

        def install
          bin.install "monstarillo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/monstarillo/monstarillo/releases/download/v0.0.301/monstarillo_0.0.301_linux_arm64.tar.gz"
        sha256 "ce49fbd8e90ce38cd5a08f9bb16227454af45a6fc4482bf622b9ae044aae425f"

        def install
          bin.install "monstarillo"
        end
      end
    end
  end

  test do
    system "#{bin}monstarillo mysql --help"
  end
end
